# Generated by Django 2.2 on 2023-10-19 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('i_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='学院编号')),
                ('i_name', models.CharField(max_length=20, verbose_name='学院名称')),
            ],
            options={
                'verbose_name': '学院信息',
                'verbose_name_plural': '学院信息',
                'db_table': 'institute',
                'ordering': ['i_name'],
            },
        ),
        migrations.CreateModel(
            name='Volunteergroup',
            fields=[
                ('vg_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='义工组织编号')),
                ('vg_name', models.CharField(max_length=20, verbose_name='义工组织名称')),
                ('vg_introduction', models.CharField(blank=True, max_length=100, null=True, verbose_name='义工组织介绍')),
            ],
            options={
                'verbose_name': '义工组织信息',
                'verbose_name_plural': '义工组织信息',
                'db_table': 'volunteergroup',
                'ordering': ['vg_name'],
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('v_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='志愿者编号')),
                ('v_pwd', models.CharField(max_length=20, verbose_name='密码')),
                ('v_name', models.CharField(max_length=10, unique=True, verbose_name='姓名')),
                ('i', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.Institute', verbose_name='学院')),
                ('vg', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.Volunteergroup', verbose_name='义工组织')),
            ],
            options={
                'verbose_name': '志愿者信息',
                'verbose_name_plural': '志愿者信息',
                'db_table': 'volunteer',
                'ordering': ['v_name'],
            },
        ),
    ]
