# Generated by Django 2.2 on 2023-10-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('av_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='活动编号')),
                ('av_title', models.CharField(max_length=20, verbose_name='活动名称')),
                ('av_state', models.DecimalField(choices=[(0, '尚未开始招募'), (1, '正在招募'), (2, '招募结束')], decimal_places=0, max_digits=4, verbose_name='活动状态')),
                ('av_request', models.CharField(max_length=100, verbose_name='活动要求')),
                ('av_content', models.CharField(max_length=100, verbose_name='活动简介')),
                ('av_starttime', models.DateTimeField(verbose_name='活动开始时间')),
                ('av_endtime', models.DateTimeField(verbose_name='活动结束时间')),
                ('av_number', models.IntegerField(verbose_name='招募总人数')),
            ],
            options={
                'verbose_name': '活动信息',
                'verbose_name_plural': '活动信息',
                'db_table': 'activity',
                'ordering': ['av_starttime'],
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('t_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='活动类型编号')),
                ('t_name', models.CharField(max_length=20, unique=True, verbose_name='活动类型名称')),
            ],
            options={
                'verbose_name': '活动类型信息',
                'verbose_name_plural': '活动类型信息',
                'db_table': 'activity_type',
                'ordering': ['t_name'],
            },
        ),
        migrations.CreateModel(
            name='Ingroup',
            fields=[
                ('g_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='举办组织编号')),
                ('g_name', models.CharField(max_length=20, unique=True, verbose_name='举办组织名称')),
            ],
            options={
                'verbose_name': '举办组织信息',
                'verbose_name_plural': '举办组织信息',
                'db_table': 'ingroup',
                'ordering': ['g_name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('l_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='地点编号')),
                ('l_name', models.CharField(max_length=20, unique=True, verbose_name='地点名称')),
            ],
            options={
                'verbose_name': '地点信息',
                'verbose_name_plural': '地点信息',
                'db_table': 'location',
                'ordering': ['l_name'],
            },
        ),
    ]
