# Generated by Django 2.2 on 2023-10-19 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('a_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='管理员编号')),
                ('a_pwd', models.CharField(max_length=20, verbose_name='管理员密码')),
                ('a_name', models.CharField(max_length=10, verbose_name='管理员名称')),
                ('i', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.Institute', verbose_name='学院')),
            ],
            options={
                'verbose_name': '管理员信息',
                'verbose_name_plural': '管理员信息',
                'db_table': 'administrator',
                'ordering': ['a_name'],
            },
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('ap_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='申请编号')),
                ('ap_time', models.DateTimeField(verbose_name='申请时间')),
                ('ap_state', models.DecimalField(blank=True, choices=[(1, '申请通过'), (2, '等待审批中'), (3, '申请不通过')], decimal_places=0, max_digits=4, null=True, verbose_name='申请状态')),
                ('ap_reason', models.CharField(blank=True, max_length=100, null=True, verbose_name='申请理由')),
                ('ap_approvaltime', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.Administrator', verbose_name='审核管理员')),
                ('av', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activity.Activity', verbose_name='申请活动')),
                ('v', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.Volunteer', verbose_name='申请志愿者')),
            ],
            options={
                'verbose_name': '申请信息',
                'verbose_name_plural': '申请信息',
                'db_table': 'apply',
                'ordering': ['ap_time'],
            },
        ),
    ]
